Repository 30th-SOPKATHON-8/Sopkathon-Android, pull requests merged in 2022-05, with the labels that each got.

#5 Feat/3
  app/build.gradle
  app/src/main/java/org/sopt/sopkathon_8_android/presentation/write/ReceiptFragment.kt
  app/src/main/java/org/sopt/sopkathon_8_android/presentation/write/WriteFragment.kt
  app/src/main/res/drawable/ic_barcode.xml
  app/src/main/res/drawable/rectangle_blue_radius_14.xml
  app/src/main/res/drawable/shape_dash_line.xml
  app/src/main/res/layout/fragment_receipt.xml
  app/src/main/res/layout/fragment_write.xml
  app/src/main/res/values/colors.xml
Labels: 윤정, feat

#6 [FEAT] #4 - Implement WriteFragment
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/sopkathon_8_android/presentation/viewmodel/WriteViewModel.kt
  app/src/main/java/org/sopt/sopkathon_8_android/presentation/write/WriteActivity.kt
  app/src/main/java/org/sopt/sopkathon_8_android/presentation/write/WriteFragment.kt
  app/src/main/res/drawable/rectangle_radius_5.xml
  app/src/main/res/drawable/rectangle_upper_radius_5.xml
  app/src/main/res/layout/activity_write.xml
  app/src/main/res/layout/fragment_receipt.xml
  app/src/main/res/layout/fragment_write.xml
  app/src/main/res/values/colors.xml
Labels: 승현, feat

#7 Feat/2
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/sopkathon_8_android/presentation/main/ItemData.kt
  app/src/main/java/org/sopt/sopkathon_8_android/presentation/main/MainActivity.kt
  app/src/main/java/org/sopt/sopkathon_8_android/presentation/main/MainItemAdapter.kt
  app/src/main/res/drawable-hdpi/main_btn_plus.png
  app/src/main/res/drawable-mdpi/main_btn_plus.png
  app/src/main/res/drawable-xhdpi/main_btn_plus.png
  app/src/main/res/drawable-xxhdpi/main_btn_plus.png
  app/src/main/res/drawable-xxxhdpi/main_btn_plus.png
  app/src/main/res/drawable/rectangle_gray_radius_10.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/item_main.xml
Labels: 지민, feat

#10 [FEAT] #8 - DataBinding 구현
  app/build.gradle
  app/src/main/java/org/sopt/sopkathon_8_android/presentation/write/ReceiptFragment.kt
  app/src/main/res/layout/fragment_receipt.xml
Labels: 윤정, feat

#11 [FEAT] #9 - Fix UI
  app/src/main/res/layout/fragment_write.xml
Labels: 승현, feat

#13 [FIX] #9 - Fix UI
  app/src/main/res/layout/fragment_write.xml
Labels: 승현, feat

#14 Feat/9
  app/src/main/res/layout/fragment_write.xml
  app/src/main/res/values/colors.xml
Labels: 승현, feat
